menu:
  #Archives: /archives
  伙伴: /friends
  关于: /aboutme

rss: /atom.xml
description: 
social:
  weibo: 
  github: https://github.com/akanezorap
  stack_overflow: 
  facebook: 
  twitter: https://twitter.com/akanezorap
  google_plus: 

page_comment: false
logo: /images/logo.jpg
background:
  cover: /images/background-cover.jpg
  color: cover-purple

archive_date_format: MMM DD
fancybox: true

google_analytics: 
baidu_tongji:
favicon: /images/logo.jpg
highlight_theme: normal
